export const PPDBSettingActionTypes = {
    API_RESPONSE_SUCCESS: '@@PPDBSetting/API_RESPONSE_SUCCESS',
    API_RESPONSE_ERROR: '@@PPDBSetting/API_RESPONSE_ERROR',

    GET_PPDBSETTING: '@@PPDBSetting/GET_PPDBSETTING',
    SHOW_PPDBSETTING: '@@PPDBSetting/SHOW_PPDBSETTING',
    UPDATE_PPDBSETTING: '@@PPDBSetting/UPDATE_PPDBSETTING',

    RESET: '@@PPDBSetting/RESET',
}
