export * from './auth/actions'
export * from './institution/actions'
export * from './master/program/actions'
export * from './setting/actions'
export * from './student/actions'
export * from './user/actions'
export * from './master/year/actions'